services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        uid: 1000
        gid: 1000
        WWWGROUP: 1000
        ADD_XDEBUG: 'N'
    ports:
      - "8888:8000"
      - "5173:5173"
      - "9003:9003"
    networks:
      - laravel
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
      - caddy_data:/data
    command: sh -c "if [ ! -d /var/www/html/vendor ]; then cp -r /var/www/html/* /var/www/html_original/; fi && supervisord -c /etc/supervisor/conf.d/supervisord.conf"

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  laravel:
    driver: bridge
